### ISSUE TITLE
Crash while trying to go to first module in Windows

### ISSUE THREAD

**Issue by MikeChuckRoast** [git-learning-game/oh-my-git#68] opened 2021-03-21 11:42 UTC
From the main menu, as soon as I click on a module, the application shuts down, and I see this error message in the command window:

ERROR: call: Refusing to delete directory C:/Users/mscannel/AppData/Roaming/Oh My Git/tmp/repos/yours/ that does not start with C:/Users/MSCANNEL/AppData/Roaming/Oh My Git/tmp/
   At: modules/gdscript/gdscript_functions.cpp:803
FATAL ERROR: Refusing to delete directory C:/Users/mscannel/AppData/Roaming/Oh My Git/tmp/repos/yours/ that does not start with C:/Users/MSCANNEL/AppData/Roaming/Oh My Git/tmp/
SCRIPT ERROR: crash: Invalid call. Nonexistent function 'fatal_error' in base 'SceneTree'.
          At: res://scenes/helpers.gdc:12
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2135
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69

**Comment by blinry** [comment] 2021-03-24 14:39
Thanks for reporting! I think this is a duplicate of #27. :)

**Closed by blinry** 2021-03-24 14:39 UTC
